### ISSUE TITLE
Miguel / Jonah Preperation

### ISSUE THREAD

**Issue by AjobK** [AjobK/Athena#8]
<h1>Preperations</h1>

- [x] Research REACT and determine if we should use it or not
- [x] What content should be viewed on post
- [x] What content should be viewed on profile
- [x] What content should be viewed on settings
- [x] What content should be viewed on about page
- [x] What content should be viewed on tutorial
- [x] How do we make user aware of cookies
- [ ] Make designs based on core design

**Comment by MiguelFieira** [comment]
# Last Updated 24/10/18 
## React

- Should we use ReactJs? **Yes**

- Why? **Because we are applying it to our other project at the moment and its more efficient to use building block to put together pieces**

### Cookies Note:

- Met Ajob besproken dat cookies waarschijnlijk een icoontje word links beneden  van je schrem met een active & inactive state.

- Make sure cookies interaction is minimal and in the law
